version: '3.8'

services:
  web:
    build: .
    image: image-complexity-generator:latest
    container_name: vision_ici_app
    ports:
      - "5000:5000"
    volumes:
      - cv_data:/app/data
    environment:
      - FLASK_ENV=production
      - DATA_DIR=/app/data
    restart: always

volumes:
  cv_data:
